### ISSUE TITLE
running 1 thread gromacs with few threads dftbplus api 

### ISSUE THREAD

**Issue by Golovin-Andrey** [tomaskubar/gromacs-dftbplus#6]
Dear  @tomaskubar 
To start dftbplus with more than 1 thread one need use flag  -DGMX_OPENMP=OFF, but gomp lib needed for libdftb+ , so again we need to modify ./src/programs/CMakeLists.txt like that:
```
find_library(GOMP         
    NAMES libgomp.so libgomp.so.1
    PATH /usr/ 
    add_library(gomp SHARED IMPORTED)
    set_target_properties(gomp PROPERTIES IMPORTED_LOCATION ${GOMP} )
    target_link_libraries(gmx libdftbplus libxmlf90 libdftd3 gfortran gomp )

```

gmx still checking for ntomp and OMP_NUM_THREADS fatal error if they are not equal.
OK, comment  lines 180-183 in src/gromacs/mdlib/gmx_omp_nthreads.cpp and line 728 in 
./src/gromacs/taskassignment/resourcedivision.cpp . Last one is to make sure that gromacs use one thread. 

- These modifications speeded up perfomance  for 59 atoms QM system from 174 ps to 230 ps per day. Gromacs 5.0 gives 142 ps.  

 - With OMP_NUM_THREADS=2 gmx running in 3 threads, that is sound logical: 1 gmx + 2 dftbplus api. 
- Scalling is bad due to small size of system.  In few days we will check on big systems , 400+ atoms
Cheers, Andrey

**Comment by tomaskubar** [comment]
Dear @Golovin-Andrey 
This looks is a good idea, so thanks for these comments, also. 
I will need to enable OpenMP for MM at some point, too, to accelerate further.
